### PR TITLE
Second attempt at codebuild configuration

### PR DESCRIPTION
**Pull request by SalusaSecondus**
Second attempt at codebuild configuration

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by SalusaSecondus** [comment]
(Not that the auto-triggered builds are in my own account but match what *will* be created by this PR.)

**Comment by SalusaSecondus** [comment]
Most recent checks will remain stuck in "Pending" because I deleted my test stack from my personal account. They all worked before but "Proofs" timed out when it had only 1 hour (rather than the new 5 hour) limit.

**Review by jargh — COMMENTED** [review]
All looks good to me

**Review by jargh — APPROVED** [review]
Approve all changes

**Pull request merged**
