### PR TITLE
Add NEON versions of functions for RSA 2048 and 4096

### PR DESCRIPTION
**Pull request by aqjune**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aqjune** [comment]
Marking this PR as a draft and waiting for the CI result

**Comment by aqjune** [comment]
benchmark.c isn't fully updated yet... will be back soon and fix it.

**Comment by aqjune** [comment]
I checked on my machine that the new 7 proofs checked fine. I couldn't run the full test because it takes quite a while; I think there is something wrong with the updated Makefile. I will look into this.

**Comment by aqjune-aws** [comment]
Closing this because this will be superceded by #73 which has better performance (and still verified).

**Pull request closed without merging**
